### ISSUE TITLE
Private gene

### ISSUE THREAD

**Issue by YutingSheep** [legumeinfo/pandagma#17]
Hi Steven,

I hope you're doing well.

I've noticed that the results from the pangenome analysis (Pandagma) don't include any private genes, and I see that about 5% of the genes remain unclustered. I have two questions regarding this:
**1. Why are 5% of the genes not clustered?
2. Could these unclustered genes be considered private genes?**

Thanks for your time, and I look forward to your insights.

Best regards,
Yuting

**Comment by StevenCannon-USDA** [comment]
Hi Yuting,

In the pandagma output, the relevant files are:
18_syn_pan_aug_extra.hsh.tsv
18_syn_pan_aug_extra_complement.fna

The ".hsh.tsv" file (or equivalently, the ".clust.tsv" file with the same prefix) lists the clustered genes.
The "complement.fna" file gives the genes that remain unclustered (given the parameters set in the config file). You could call these "private" -- though you would need to qualify that label as being relative to the chosen parameters. Different parameters will give different proportions that are clustered or not clustered.

Let me know if you have other questions about this -
Steven

**Comment by YutingSheep** [comment]
Hi Steven,

Thank you for your helpful response. I really appreciate it!

Regards,
Yuting
